[buildPlans.IosevkaManet]
family = "Iosevka Manet"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaManet.variants]
  inherits = "ss07"

  [buildPlans.IosevkaManet.ligations]
  inherits = "dlig"

[buildPlans.IosevkaManet.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaManet.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaManet.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaManet.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaManet.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
