# Fix theme contrast
set-face global   PrimarySelection black,blue+F
set-face global SecondarySelection black,green+F
set-face global     MenuForeground black,blue+d
set-face global     MenuBackground black,white
set-face global           MenuInfo black

# Add line numbers
add-highlighter global/ln number-lines -relative -hlcursor -separator "  " -min-digits 3
set-face global LineNumberCursor yellow,default,default

# Highlight all search matches
add-highlighter global/search dynregex '%reg{/}' 0:+b

# Add soft-wrapping
add-highlighter global/wrap wrap -word -indent -width 80 -marker ' -> '

# Make cursor yellow on Insert mode
hook global BufCreate .* %{
    hook buffer ModeChange (push|pop):insert:.* %{
        set-face buffer PrimaryCursor black,white
    }
    hook buffer ModeChange (push|pop):.*:insert %{
        set-face buffer PrimaryCursor black,yellow
    }
}

# Fix indenting
hook global WinSetOption filetype=(?!makefile).* %{
    map global insert <tab> '<a-;><a-gt>'
    map global insert <s-tab> '<a-;><a-lt>'
}

# Start LSP
eval %sh{kak-lsp}
lsp-enable
